name: Compile micro-benchmark
description: Build the pinned micro-benchmark binary
runs:
  using: composite
  steps:
    - name: Install crates
      shell: bash
      working-directory: ${{ env.SOURCE_DIRECTORY }}
      run: pnpm install --frozen-lockfile --filter pacquet
    - name: Compile
      shell: bash
      working-directory: ${{ env.SOURCE_DIRECTORY }}
      run: cargo build --release --bin=micro-benchmark
