allowBuilds:
  nx: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@nx/nx-darwin-arm64@23.2.0'
  - '@nx/nx-darwin-x64@23.2.0'
  - '@nx/nx-freebsd-x64@23.2.0'
  - '@nx/nx-linux-arm-gnueabihf@23.2.0'
  - '@nx/nx-linux-arm64-gnu@23.2.0'
  - '@nx/nx-linux-arm64-musl@23.2.0'
  - '@nx/nx-linux-x64-gnu@23.2.0'
  - '@nx/nx-linux-x64-musl@23.2.0'
  - '@nx/nx-win32-arm64-msvc@23.2.0'
  - '@nx/nx-win32-x64-msvc@23.2.0'
  - nx@23.2.0
